name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/two-tier-flask-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/two-tier-flask-app:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 -d > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: /tmp/ssh_key
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/two-tier-flask-app:latest
            docker stop two-tier-flask-app || true
            docker rm two-tier-flask-app || true
            docker run -d -p 5000:5000 --name two-tier-flask-app \
              -e MYSQL_HOST=mysql \
              -e MYSQL_USER=root \
              -e MYSQL_PASSWORD=root \
              -e MYSQL_DB=mydb \
              ${{ secrets.DOCKER_USERNAME }}/two-tier-flask-app:latest
